apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-ui
  labels:
    app: streamlit-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit-ui
  template:
    metadata:
      labels:
        app: streamlit-ui
    spec:
      containers:
      - name: streamlit-ui
        image: kumarsankalp/catdog:latest
        imagePullPolicy: IfNotPresent
        command: ["streamlit", "run", "app/ui.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
        env:
        - name: API_URL
          value: "http://mlops-inference-service:8000"
        ports:
        - containerPort: 8501
